### ISSUE TITLE
Provide encoding check for a document

### ISSUE THREAD

**Issue by svaningelgem** [vaites/php-apache-tika#15]
For now I can see my encoding is under getMetaData['meta']['Content-Encoding'].

But I saw in Tika, there is something called [EncodingDetector](https://tika.apache.org/1.20/api/org/apache/tika/detect/EncodingDetector.html).

Maybe we could use it to check the Encoding of a given data set?

**Comment by vaites** [comment]
I don't understand your question. There's no API call for encoding only on [Apache Tika server](https://wiki.apache.org/tika/TikaJAXRS) so the only way to detect it is throug getMetaData() method...

You can use it with any data. If is in a variable, just put in a temporary file and pass its path to Apache Tika client...

**Comment by svaningelgem** [comment]
I checked the URL you gave, and it seems it's not explicitly exposed. (but it is available through /meta)

So my question evolves :-) : Is it possible to add an additional variable $encoding within the Metadata \Vaites\ApacheTika\Metadata class that is filled up by the "Content-Encoding" field?

Thanks!

**Comment by svaningelgem** [comment]
[patch.txt](https://github.com/vaites/php-apache-tika/files/2993938/patch.txt)

**Comment by vaites** [comment]
Thanks @svaningelgem, will take a look in all three issues ;)

**Comment by vaites** [comment]
Fixed in 4b4be8c4cae30c71f7dc9e9bc61c2693e0f9651d
