### ISSUE TITLE
Consider adding Dockerfile for development environment

### ISSUE THREAD

**Issue by peter279k** [vaites/php-apache-tika#20]
To make developers easy to build this package development environment, I think we can consdier adding this `Dockerfile` to resolve this issue.

**Comment by vaites** [comment]
I don't understand how do you want to use Docker here. Can you explain, please?. Do you want a container where test against without installing Java in your device?

**Comment by peter279k** [comment]
> I don't understand how do you want to use Docker here. Can you explain, please?. Do you want a container where test against without installing Java in your device?

That's right. To make developers easy to setup the container with Apache Tika environment.

**Comment by vaites** [comment]
If you want only Apache Tika, there are containers like this: https://github.com/LogicalSpark/docker-tikaserver

Is what you need?

**Comment by peter279k** [comment]
@vaites, thanks for your this Docker container reference.

I will check that and close this issue :).
