### ISSUE TITLE
small code issue

### ISSUE THREAD

**Issue by filerun** [vaites/php-apache-tika#21]
\Vaites\ApacheTika\Client::checkRequest being used statically in /Vaites/ApacheTika/Clients/CLIClient.php, line 160, while using $this

**Comment by vaites** [comment]
Thanks @filerun, you're right. Will release a fix soon.

**Comment by vaites** [comment]
Fixed in 75fa003c410674edc4124debbc44f1fdbf9f074f, will publish it in the next release because doesn't throws any warning/notice.
