### ISSUE TITLE
getText or getHTML only returns first page content

### ISSUE THREAD

**Issue by stouch** [vaites/php-apache-tika#25]
Hello,

When I do :
```
$client = \Vaites\ApacheTika\Client::make('localhost', 9797);
$text = $client->getHTML('../<filename>.docx');
```
```$text ``` only contains text of the first page of my document, is this normal ?

Thanks.

**Comment by vaites** [comment]
No, it must return all the content. Can you upload or send the file?. Anyway what PHP and Apache Tika versions are you using?

**Comment by stouch** [comment]
It's a private file, I'm gonna send it to you using Twitter ,
I use http://apache.crihan.fr/dist/tika/tika-server-1.23.jar and latest version of php-apache-tika

**Comment by vaites** [comment]
Perfect, thanks.

Only happens with this file or with any file?

**Comment by vaites** [comment]
After some tests it seems an Apache Tika issue, because the Tika app returns the same results.
