### ISSUE TITLE
Bindings support for Tika library

### ISSUE THREAD

**Issue by qwertynik** [vaites/php-apache-tika#29]
Does this library contain bindings for all possible usage of the Tika library?

**Comment by vaites** [comment]
No, not all Apache Tika features are supported, but very few are not supported. I don't have a "compatibility table". Is there any specific functionality you need?

**Comment by qwertynik** [comment]
Thanks for your response @vaites. 
No specific functionality. Wanted to understand the limitations of the library before using it.

**Comment by vaites** [comment]
This library is focused on text extraction. The only "main" functionality not supported is translation...
