### ISSUE TITLE
Tag 0.3.1

### ISSUE THREAD

**Issue by welcoMattic** [vaites/php-apache-tika#3]
Is it possible to tag a minor version 0.3.1, to be able to use getVersion method?

**Comment by vaites** [comment]
Version tagged, sorry for the delay...

**Comment by vaites** [comment]
Sorry sorry sorry!. I forgot to update composer.json with the previous version, so package in Composer did not update. I tagged version 0.3.2 now and you can update it from composer. Sorry again!

**Comment by welcoMattic** [comment]
No problem, but you can must remove `version`of composer.json for a published package. Then you will never forget to increment version in composer.json. Only on git.

**Comment by vaites** [comment]
Oh, didn't know this. I always put version on composer.json but never readed this part of Composer docs. Thanks!
