### ISSUE TITLE
Documentation issue - encoding

### ISSUE THREAD

**Issue by yourpropertyexpert** [vaites/php-apache-tika#30]
The main documentation (README.md) contains the text:

> Encoding
> By default the returned text is encoded with UTF-8 but there are some issues with the encoding when using the app mode. The Client::setEncoding() method allows to set the expected encoding **(this will be fixed in the upcoming 1.0 release)**.

The final bit (highlighted above in bold) either needs updating with a new release number, or (probably) just deleting.

**Comment by vaites** [comment]
Thanks @yourpropertyexpert, I need to remove the bold text, the 1.0 version works well with UTF-8.

**Comment by vaites** [comment]
Just updated the README.md. Thanks!
