### ISSUE TITLE
X-Tika-OCRLanguage

### ISSUE THREAD

**Issue by aleksanm** [vaites/php-apache-tika#31]
If there's an option to set more then one (default eng) OCR language?

**Comment by vaites** [comment]
There's no _easy_ way to do it yet. Meanwhile you can add it with cURL options:

```php
$client = Client::make('localhost:9998');
$client->setOption(CURLOPT_HTTPHEADER, 'X-Tika-OCRLanguage: eng+fra');
```

I will add soon specific methods to set HTTP headers and OCR languages.

**Comment by vaites** [comment]
I added specific methods on the v1.2.0 release. Thanks!
