### ISSUE TITLE
Support for --text-main?

### ISSUE THREAD

**Issue by kapunakap** [vaites/php-apache-tika#5]
Hey, I know there's --text-main in Tika-app, how about Tika-server?

**Comment by vaites** [comment]
This function is not documented on server mode. I looked at source code and seems unimplemented, so will ask in Tika community.

**Comment by kapunakap** [comment]
Hey man, I already did: https://issues.apache.org/jira/browse/TIKA-2343

**Comment by vaites** [comment]
Great, keep me informed then...

**Comment by kapunakap** [comment]
This is now possible. Tika 1.15 has been released today. Please see this: https://issues.apache.org/jira/browse/TIKA-2343

**Comment by vaites** [comment]
Thanks Nico,  I expected to have more time until the new version. I'm working on this feature and secuencial read, will release both soon. 

Meanwhile, can you provide an example of document or file that needs text-main?. I need a new sample for this feature, so if you have one will save me some time...

**Comment by kapunakap** [comment]
> Meanwhile, can you provide an example of document or file that needs text-main?. I need a new sample for this feature, so if you have one will save me some time...

Absolutely: https://drive.google.com/open?id=0B7AKQvQJ6zw2M3ZWaWNOaUI1T00

**Comment by kapunakap** [comment]
Awesome

**Comment by vaites** [comment]
The 0.3.7 version is released with this feature. Thanks for your suggestion.

**Comment by kapunakap** [comment]
Thank you for the implementation!

**Comment by kapunakap** [comment]
I just implemented this on my end, works as should. Just wanted to let you know.
