### ISSUE TITLE
CLIClient fails on Windows 

### ISSUE THREAD

**Issue by caugner** [vaites/php-apache-tika#9]
I tried to use the CLIClient on Windows, but got two problems:

1. The file `/tmp/tika-error.log` does not exist, which yields a warning [1].
2. The Windows Commandline doesn't seem to like the single quotes around the paths, which yields an error [2].
 
[1] `Warning: proc_open(/tmp/tika-error.log): failed to open stream: No such file or directory in C:\path\to\my\application\vendor\vaites\php-apache-tika\src\Clients\CLIClient.php on line 120`
[2] `Error: Unable to access jarfile 'C:\path\to\my\application\bin\tika.jar'`

Solutions:
1. Use [`sys_get_temp_dir()`](https://secure.php.net/manual/en/function.sys-get-temp-dir.php) instead of `"/tmp/"` [here](https://github.com/vaites/php-apache-tika/blob/7ee6c4de72846c8b2101065293cb0eddb7aa10c0/src/Clients/CLIClient.php#L115-L119).
2. Use [`escapeshellargs()`](https://secure.php.net/manual/en/function.escapeshellarg.php) instead of single quotes [here](https://github.com/vaites/php-apache-tika/blob/7ee6c4de72846c8b2101065293cb0eddb7aa10c0/src/Clients/CLIClient.php#L81-L85).

I will submit a PR in a minute.

**Comment by vaites** [comment]
Thanks @caugner, I don't test all the features in Windows yet. Will review your patch and release the fixes ASAP.

**Comment by vaites** [comment]
Merged and released new version. Thanks!
